version: '3.9'
services:
  app:
    image: nginx:latest
    container_name: app
    ports:
      - 80:80
    depends_on:
      - pg
    networks:
      - app-network
  pg:
    image: postgres:15.0-alpine
    container_name: database
    ports:
      - 5432
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
