version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
#    image: nurulyakin/demo:v1.0.0
    container_name: demo-app
    ports:
      - 8800:80
    networks:
      - demo-network
    depends_on:
      - db
      - cache
  db:
    image: mysql:8.0
    container_name: demo-db
    restart: always
    environment:
      MYSQL_DATABASE: demo-db
      MYSQL_USER: user-db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306
    networks:
      - demo-network
  cache:
    image: memcached:latest
    container_name: demo-cache
    restart: always
    ports:
      - 11211
    networks:
      - demo-network
networks:
  demo-network:
    driver: bridge
